### ISSUE TITLE
How to finetune AnchorDETR on custom dataset?

### ISSUE THREAD

**Issue by ducvuuit** [megvii-research/AnchorDETR#1]

**Comment by tangjiuqi097** [comment]
Hi, you can refer to this [gist](https://gist.github.com/m-klasen/651297e28199b4bb7907fc413c49f58f) and the discussion in issues [#9](https://github.com/facebookresearch/detr/issues/9) and [#205](https://github.com/facebookresearch/detr/issues/205) of the DETR.

**Comment by tangjiuqi097** [comment]
I'm closing this issue as I think I have answered your question, but let us know if you have further questions.
