### ISSUE TITLE
onnx model can not be simpiflied and pass onnx.check and wierd output

### ISSUE THREAD

**Issue by jinfagang** [megvii-research/AnchorDETR#10]
the onnx model exported has very wierd dimension caused it can not be simplifed or pass onnx.checker.check.

This is verbose output of export DETR:

![image](https://user-images.githubusercontent.com/21303438/137290123-172e8e1d-89f7-4918-ab93-41dc90583ce6.png)

this is verbose output of AnchorDETR:

![image](https://user-images.githubusercontent.com/21303438/137290182-246c0153-f4c9-4007-ae57-688a6220b943.png)

Both **are last serveral layers**, as you can see, for DETR the strides seems very small

but AnchorDETR are something like `Float(1, 1, 900, 91, strides=[81900, 81900, 91, 1], requires_grad=1, device=cuda:0)` gaint value.

and it caused when try to check this model, or try to simplifed this model:

```
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3714028571

```

error got.

any idea?

**Comment by tangjiuqi097** [comment]
@jinfagang  Hi, 

> if you try inference anchordetr onnx model you will found your result will all be Nan.

This problem may be the same as issue [#49](https://github.com/facebookresearch/detr/issues/49#issuecomment-663487353) in DETR and I will fix it as they do. But I am not sure if the problem of simplifier is related to it.

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/137473640-89d4e2a9-7cd0-42ae-8a9b-e83397a1d167.png)

Now looks normal, I will do trt acceleration later.
