### ISSUE TITLE
AP stops at 30 at iteration 250000

### ISSUE THREAD

**Issue by luohao123** [megvii-research/AnchorDETR#19]
I trained 250000 iterations, but the AP can not even goes up anymore..

![image](https://user-images.githubusercontent.com/49749220/140879588-1f41e7f8-ed36-44c9-afae-c64024e3ea5a.png)

With bs=80, lr=0.00025 

same bs can help DETR achieve 40 AP

**Comment by tangjiuqi097** [comment]
Duplicate as [#20](https://github.com/megvii-research/AnchorDETR/issues/20).
