### ISSUE TITLE
Some questions about your code 

### ISSUE THREAD

**Issue by Huzhen757** [megvii-research/AnchorDETR#2]
Hi, I'm very interested in your work about the newly decoder and self-attention of  DETR，but  I have some questions about your code.
         1.  when I debug the code,  I found a detail not mentioned in the paper：when use RCDA attention, it is divided into two situations, like this :
`if efficient_compute:
        if src_len_col<src_len_row:
            b_ein,q_ein,w_ein = attn_output_weights_row.shape
            b_ein,h_ein,w_ein,c_ein = v.shape
            # Ax * V得到论文中的Z [bs*8,HW,H*32] -> [bs*8, H, HW, 32]
            attn_output_row = torch.matmul(attn_output_weights_row,v.permute(0,2,1,3).reshape(b_ein,w_ein,h_ein*c_ein)).reshape(b_ein,q_ein,h_ein,c_ein).permute(0,2,1,3)
            # Ay * Z得到论文中的attention outputs: [HW,8,bs,H]*[HW,bs*8,H,32] -> [HW,8,bs,32] -> [HW,8*bs,32] -> [HW, bs, 256]
            attn_output = torch.matmul(attn_output_weights_col.permute(1,0,2)[:,:,None,:],attn_output_row.permute(2,0,1,3)).squeeze(-2).reshape(tgt_len,bsz,embed_dim)
            ### the following code base on einsum get the same results
            # attn_output_row = torch.einsum("bqw,bhwc->bhqc",attn_output_weights_row,v)
            # attn_output = torch.einsum("bqh,bhqc->qbc",attn_output_weights_col,attn_output_row).reshape(tgt_len,bsz,embed_dim)
        else:
            b_ein,q_ein,h_ein=attn_output_weights_col.shape
            b_ein,h_ein,w_ein,c_ein = v.shape
            attn_output_col = torch.matmul(attn_output_weights_col,v.reshape(b_ein,h_ein,w_ein*c_ein)).reshape(b_ein,q_ein,w_ein,c_ein)
            attn_output = torch.matmul(attn_output_weights_row[:,:,None,:],attn_output_col).squeeze(-2).permute(1,0,2).reshape(tgt_len, bsz, embed_dim)`

Why is there two cases to calculate RCDA Attention outputs, in the code， if col < row,  Z = Ax * V，then outputs = Ay * Z；
if col > row,  Z = Ay * V,  then outputs = Ax * Z。in my opinion， when col < row, the attention outputs = Ay * Ax * V , otherwise  the outputs = Ax * Ay * V，What is the reason for this design?

2.   RCDA attention module is only used in Self-Attention of Encoder and Cross-Attention of Deocder，Why not use it in Self-Attention of Decoder？
I sincerely  hope I can get your answers！ Thanks ！

**Comment by tangjiuqi097** [comment]
Hi,

1. In the paper, we hypothesize W ≥ H and compute row attention first without losing generality. If H≥W，we should computer column attention first instead. The orders of calculation do not affect the results so that we can use either of them. 
But it can affect memory. The temporary result **Z** is in the size of (N<sub>q</sub>, H, C) when computing row attention first, or (N<sub>q</sub>, W, C) when column first. So if W ≥ H, compute row attention first can save more memory.

2. 
    -  If we use the learned anchor points, it seems not easy to decouple it to row feature and column feature.
    -  Although we can apply RCDA to the decoder self-attention with the grid anchor points, it will not save memory if the number is smaller than 32x32 as analyzed in the paper.

**Comment by Huzhen757** [comment]
OK，I know，thanks for your carefully reply。

**Comment by Huzhen757** [comment]
好的，我已经明白了，感谢您的回复，但是我使用您提供的预训练权重在resnet-50DC5为backbone，测试了模型在COCO2017-val数据集上的精度，结果如下：





这里我使用的batch size为2进行测试的，但是其中的AP和AP50与论文中提供的实验结果，都低了4个点左右，请问这是什么原因呢？是使用了Multi-scale&nbsp;test或者是其他的什么trick吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/AnchorDETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午3:46
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/AnchorDETR] Some questions about your code  (#2)





 
Hi,
  
 
In the paper, we hypothesize W ≥ H and compute row attention first without losing generality. If H≥W，we should computer column attention first instead. The orders of calculation do not affect the results so that we can use either of them.
 But it can affect memory. The temporary result Z is in the size of (Nq, H, C) when computing row attention first, or (Nq, W, C) when column first. So if W ≥ H, compute row attention first can save more memory.
 
 
  
If we use the learned anchor points, it seems not easy to decouple it to row feature and column feature.
 
Although we can apply RCDA to the decoder self-attention with the grid anchor points, it will not save memory if the number is smaller than 32x32 as analyzed in the paper.
  
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tangjiuqi097** [comment]
Hi, 

You can refer to the issue [#239](https://github.com/facebookresearch/detr/issues/239) of DETR.

Quoting @alcinos


> However, I want to stress that a model trained with bs=1 per card won't do well if tested with bs > 1. The reason is that it will never have encountered padding at train time, and thus will be confused when encountering it at test time.

**Comment by Huzhen757** [comment]
OK，thank you very much!&nbsp;when&nbsp;I&nbsp;use&nbsp;batch&nbsp;size=1&nbsp;test&nbsp;the&nbsp;DC5-model，the&nbsp;AP&nbsp;index&nbsp;is completely similar to that in the paper！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/AnchorDETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月25日(星期六) 晚上10:26
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/AnchorDETR] Some questions about your code  (#2)





 
Hi,
 
You can refer to the issue #239 of DETR.
 
Quoting @alcinos
  
However, I want to stress that a model trained with bs=1 per card won't do well if tested with bs &gt; 1. The reason is that it will never have encountered padding at train time, and thus will be confused when encountering it at test time.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tangjiuqi097** [comment]
I'm closing this issue as I think I have answered your question, but let us know if you have further questions.

**Comment by Huzhen757** [comment]
OK，Thank&nbsp;you&nbsp;very&nbsp;much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/AnchorDETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月26日(星期天) 中午11:17
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/AnchorDETR] Some questions about your code  (#2)





 
I'm closing this issue as I think I have answered your question, but let us know if you have further questions.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
