### ISSUE TITLE
How to get the 151 GFLOPs?

### ISSUE THREAD

**Issue by charlesCXK** [megvii-research/AnchorDETR#22]
Hi, thank you for doing such nice work! May I ask how to get the number of GFLOPs in Table 1? I got 172G using the same strategy of DETR (average on the first 100 images of COCO val set). Thanks!

**Comment by charlesCXK** [comment]
I use `FlopCountAnalysis` in detectron2, which has different rules with the tool in this repo.

**Comment by tangjiuqi097** [comment]
Thanks for your reminder. We follow the script in the [#110](https://github.com/facebookresearch/detr/issues/110#issuecomment-650759821) of DETR with a few modifications. We will update the repo and the paper at the next version by using the FlopCountAnalysis in detectron2, as we think it is more widely used.
