### ISSUE TITLE
How many encoder and decoder layers used in AnchorDETR?

### ISSUE THREAD

**Issue by jinfagang** [megvii-research/AnchorDETR#3]
Does EfficientDETR simplified decoder applicable to AnchorDETR push further speed effiency?

**Comment by tangjiuqi097** [comment]
Hi, 

We use 6 encoder layers and 6 decoder layers like DETR. 

It seems that the EfficientDETR is based on the Deformable DETR. As the attention in the Deformable DETR is not in the query, key, value manner like the standard attention in DETR, I am not sure if the method in EfficientDETR can be applicable to Ours. Maybe someone can try it when the code of EfficientDETR is available.

**Comment by jinfagang** [comment]
@tangjiuqi097 thanks, since this code released under megvii, and efficientDETR also megvii's work, though your works maybe share some common knowledges. 

what's the speed boost comes from in AnchorDETR mainly?

**Comment by tangjiuqi097** [comment]
@jinfagang These two works are done independently and concurrently by different teams and it seems that the two works are very unrelated. 

The speed boost of AnchorDETR comes from the RCDA for high resolution features.

**Comment by jinfagang** [comment]
I know RCDA, does AnchorPoint also accelerated speed? Since it seems don't need a pos embed layer there.

**Comment by jinfagang** [comment]
@tangjiuqi097 Also, I have another question, I saw there only reported level=1 which is DC5 or C5 feature output result, but detr original using multi-level, although it have better performance with single level, but:

1) Did u tested with multi-level? Does it obtain better performance?
2) Does using multi-level still faster than DETR?

**Comment by tangjiuqi097** [comment]
@jinfagang  Hi,

The anchor points will not affect the inference speed. They are encoded as the object queries and should have the same speed as the learned query embeddings. The object queries are treated as the position embeddings.   

It seems that DETR does not use multiple-level features. The standard attention in it will cost lots of memory when using the high-resolution feature. 

I have tried a simple implementation of using the multi-level feature, and of course, it can obtain better performance and slower speed than the single DC5 feature (e.g. 45.2AP, 11FPS).

**Comment by jinfagang** [comment]
@tangjiuqi097 From official detr d2 version, seems they using 4 levels: https://github.com/facebookresearch/detr/blob/fe752a89b352284c7395dbb629bedaa64271b0f4/d2/configs/detr_256_6_6_torchvision.yaml#L10

And when obtain mask and srcs, they have a operation like:

```
masks = self.mask_out_padding(
    [features_per_level.shape for features_per_level in features.values()],
    images.image_sizes,
    device,
)
assert len(features) == len(masks)
for i, k in enumerate(features.keys()):
    features[k] = NestedTensor(features[k], masks[i])
return features
```

I logged the levels here, it have 4 different outputs. Do u have any idea.

**Comment by tangjiuqi097** [comment]
@jinfagang Hi, I have not tested the code of the DETR d2 version, but I think this version seems to be the DETR-R50-C5.
Although the backbone outputs multiple-level features, DETR only uses the C5 feature. You can refer to this [line](https://github.com/facebookresearch/detr/blob/fe752a89b352284c7395dbb629bedaa64271b0f4/models/detr.py#L63).

**Comment by jinfagang** [comment]
@tangjiuqi097 Oh, then actually, d2 version also using just one layer. C5 it also have an operation:

```
features, pos = self.backbone(samples)
# print(features, 'features')

src, mask = features[-1].decompose()
assert mask is not None
hs = self.transformer(self.input_proj(src), mask, self.query_embed.weight, pos[-1])[0]
```
So, multi level actually very time consuming?

**Comment by tangjiuqi097** [comment]
@jinfagang  Multi-level features, especially the high-resolution features, will cost more memory and calculation.

**Comment by jinfagang** [comment]
@tangjiuqi097 Strange thing, I found export your version to onnx got a very strange error:

```
RuntimeError: 0INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":533, please report a bug to PyTorch. We don't have an op for aten::fill_ but it isn't a special case.  Argument types: Tensor, bool, 

```

While original DETR export onnx works very smoothy, any idea?

**Comment by tangjiuqi097** [comment]
@jinfagang I am sorry that I've never used onnx. Maybe you can report a bug to PyTorch as the error message suggests.

**Comment by jinfagang** [comment]
OK, it's not a bug of pytorch, just some of anchordetr code can not be traced. that's pity

**Comment by tangjiuqi097** [comment]
It may be because there are some [control flow operators](https://github.com/megvii-research/AnchorDETR/blob/7b1f11c6b8946dd9821d1c080657a488e8fdd9ae/models/transformer.py#L313-L326). But I would like to keep it as I hope users can choose to use either the RCDA or the standard attention. 

I may fix it at another branch in the future. We also welcome the community to contribute to the code.

**Comment by jinfagang** [comment]
@tangjiuqi097 that's nice, it might caused by some assign written styles in pytorch, maybe just change a line code can get rid of this error, I have occured this error before, but I forgot have to resolved it, it was caused in mask generate step in DETR, but AnchorDETR doesn't have this step, so have no idea what else could go wrong. Maybe happend exactly in RCDA part code.

Anyway, a transformer based model can not be accelerated by tensorrt, it would be very pity since in my experiences tensorrt can have up to 5X speed up at these models, such as DETR.

**Comment by tangjiuqi097** [comment]
@jinfagang I have updated the code to support torchscript as this [gist](https://gist.github.com/tangjiuqi097/d450a728194622f33a25223822cde14a). I guess it may helpful for the ONNX. You can update the code to the corresponding file and run the `test_torchscript.py` to try it.

**Comment by jinfagang** [comment]
@tangjiuqi097 Can u push these modfication to this repo so that others can see what changed and directly try this feature without copy and paste from another gist?

**Comment by jinfagang** [comment]
@tangjiuqi097 I don't understand, did u said export to torchscript doesn't using RCDA? why they imcompatible to your main repo? Maybe you can check a new branch to do so? ....

Your gist is nice but I totally don't understand which file means what....

**Comment by jinfagang** [comment]
@tangjiuqi097 let me have a test, did you tested using RCDA works on torchscript tracing?

**Comment by jinfagang** [comment]
@tangjiuqi097 I found previous problem is not caused by code, but pytorch version, for torch1.9+ still can not trace, but with torch1.8 everything works OK.

However, I found the exported onnx can not be simplified (via onnx-simplifier):

```
    protobuf_string = model if isinstance(model, binary_type) else model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3714028571

```

which no clue to found why, since the onnx generated size is normal 132M about.
