### ISSUE TITLE
Details about GFLOPs

### ISSUE THREAD

**Issue by volgachen** [megvii-research/AnchorDETR#30]
Excuse me, I would like to know how these `GFLOPs` are calculated. Could you provide the information, such as the input resolution?

**Comment by tangjiuqi097** [comment]
Hi, the FLOPs is the average of the first 100 images in the val set and the input resolution of each image follows the standard (800, 1333) transform. You can refer to the [code](https://github.com/megvii-research/AnchorDETR/blob/c39246b8e8001179a18996dff0bcf1d78598deb8/compute_flops.py) or the previous [code](https://github.com/megvii-research/AnchorDETR/blob/a5418ea3ccfe0ab4ce2bfb60cd01b4389b1a9c63/compute_flops_and_speeds.py) for more detail.

**Comment by volgachen** [comment]
Thank you. I will look into the code.
