### ISSUE TITLE
Hello the default model is AnchorDETR-C5 or AnchorDETR-DC5 ?

### ISSUE THREAD

**Issue by cxq1** [megvii-research/AnchorDETR#34]
Hello the default model is AnchorDETR-C5 or AnchorDETR-DC5 ?

**Comment by tangjiuqi097** [comment]
Hi, the default model is AnchorDETR-DC5.

You can modify the dilation in this [line](https://github.com/megvii-research/AnchorDETR/blob/f2be2163c4f5ce5c7981e6146428155e64dc097c/main.py#L53) if you want to use the C5 feature.
