### ISSUE TITLE
Why not input updated reference points to next layer decoder?

### ISSUE THREAD

**Issue by JarvisUSTC** [megvii-research/AnchorDETR#35]
Hi! This work is very interesting. After I read the code, I find output_coordinates are gotten by prediction head of every layer for helping training but the reference points are always invariant. Why not update the reference points by the prediction head like Deformable DETR? I think it is more natural.

**Comment by tangjiuqi097** [comment]
Thanks for your advice. We have not updated the points to keep the algorithm simple and for a fair comparison with the DETR, SMCA and Condition DETR, etc. We may try it in the future.

**Comment by JarvisUSTC** [comment]
Thanks for your reply. Look forward your next work!
