### ISSUE TITLE
Hello! The Feature position in figure3 is the positional encoding in DETR

### ISSUE THREAD

**Issue by cxq1** [megvii-research/AnchorDETR#36]
Hello! The Feature position in figure3 is the positional encoding in DETR

**Comment by tangjiuqi097** [comment]
No, the feature position is the normalized grid position of the image feature map.
For example, if the shape (H, W) of feature map is 4x5, then the feature position is:
![image](https://user-images.githubusercontent.com/22868536/159220071-10b637c5-b36a-4649-9d12-04766047087e.png)

You can refer to the [code](https://github.com/megvii-research/AnchorDETR/blob/f3fdc7cc143fa00f615c61484cee45eac03a6f94/models/transformer.py#L124) for more detail.
