### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by jiangyichen19** [megvii-research/AnchorDETR#37]
博主你好，我最近在复现您的模型，根据你的readme文件，下载了模型参数，并运行了eval的代码
1.python main.py --eval --coco_path /data/coco --resume /weights/AnchorDETR_r50_c5.pth
但是发现选择eval模式进行测试的时候，并不会使用coco的测试数据集，而是使用的coco的训练集进行测试。

**Comment by tangjiuqi097** [comment]
我测试了一下，应该是没有问题。加上‘--eval’是用val集测试，不会用训练集。如果还有问题，可以发一下log信息。另外，默认的setting是dc5模型，模型应该加载对应的dc5模型，或者把dilation参数改一下

**Comment by jiangyichen19** [comment]
感谢您的回复，但是我试了一下，好像还是有问题，我的操作步骤如下 
1.执行：python main.py --eval --coco_path ./data2017/coco --resume ./weights/AnchorDETR_r50_dc5.pth
2.报错：
   self.coco = COCO(annFile)
  File "D:\Programfiles\Anaconda\envs\torch7.7\lib\site-packages\pycocotools\coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data2017\\coco\\annotations\\instances_train2017.json'

我的疑问:我已经准备好了测试集的数据标签，但是不知道为什么会调用coco.py，我觉得测试调用的应该是coco_eval.py，而且有无instances_train2017.json应该都不影响吧，为什么会报错呢？我该怎么解决呢？

**Comment by jiangyichen19** [comment]
好的，很感谢你的回复，但我有几个不明白的地方，
1.如果仅仅测试的话，按道理来说只要有测试数据集和权重就够了，但是为什么好像确实train数据集就会报错。
2.我的电脑是3060（6G），结果测试的时候显存好像爆了。。。，但实际上，我感觉不应该啊,仅仅测试的话也需要这么大的显存吗？

**Comment by jiangyichen19** [comment]
感谢回复，我测试了，确实可以，但看了一下代码，好像预测的图片无法保存是吗？

**Comment by tangjiuqi097** [comment]
是的，一般来说不会保存图片，不过在--eval模式下，我们保存了json结果在--output_dir目录下，您可以用[detectron2的可视化代码](https://github.com/facebookresearch/detectron2/blob/main/tools/visualize_json_results.py)来可视化结果。

**Comment by jiangyichen19** [comment]
再次感谢您的回复，我看了代码，理论上是会保存一个json文件
`
parser.add_argument('--output_dir', default='/output',
                        help='path where to save, empty for no saving')
`
`    if args.eval:
        test_stats, coco_evaluator = evaluate(model, criterion, postprocessors,
                                              data_loader_val, base_ds, device, args.output_dir, save_json=True)
        if args.output_dir:
            utils.save_on_master(coco_evaluator.coco_eval["bbox"].eval, output_dir / "eval.pth")
            if utils.is_main_process():
                with open(os.path.join(args.output_dir, 'results.json'), 'w') as f:
                    json.dump(coco_evaluator.results['bbox'], f)
        return`
但不知道为什么，我测试完之后，在我设置的 output文件夹下面下没有看到json文件，这让我感到疑惑，尝试了几次之后，还是没有

**Comment by tangjiuqi097** [comment]
可能有两个原因：一个是需要在`--eval`模式下才会保存；另一个可能是您的保存路径 `/output` 在根目录下可能没有写权限，可以换个路径试一试。
