### ISSUE TITLE
The comparison with DETR

### ISSUE THREAD

**Issue by superwj1990** [megvii-research/AnchorDETR#39]
Hi, in the paper, you compare the method with DETR in Table 2. By default, the final query num of yours is 900 while DETR is 100, it seems no fairly enough? Did you test the result when the query num of DETR is 900? Looking forward to your reply, thanks~

**Comment by tangjiuqi097** [comment]
Hi, more queries for DETR are not helpful and it will hurt the convergence speed (worse performance with the same training epoch). You can refer to [#166](https://github.com/facebookresearch/detr/issues/166#issuecomment-666522696) in DETR. 

You can also refer to Table 4 in our paper, in which we have discussed the number of queries.
