### ISSUE TITLE
Why GroupNorm in  self.input_proj ?

### ISSUE THREAD

**Issue by liming-ai** [megvii-research/AnchorDETR#43]
https://github.com/megvii-research/AnchorDETR/blob/0b4358a1caacf4b311b8653312e145f1c94de3d3/models/anchor_detr.py#L66

I noticed that in original DETR and Deformable DETR, input_proj does not use GroupNorm, what is the reason for using it here?

**Comment by tangjiuqi097** [comment]
Hi, we follow the [Deformabel DETR](https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/deformable_detr.py#L79) to use the GroupNorm. We have not explored the effect of it.

**Comment by liming-ai** [comment]
> Hi, we follow the [Deformabel DETR](https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/deformable_detr.py#L79) to use the GroupNorm. We have not explored the effect of it.

Sorry to bother you for my mistake, nice work!
