### ISSUE TITLE
How to replace resnet50 with your own backbone

### ISSUE THREAD

**Issue by yao-zheng-yi** [megvii-research/AnchorDETR#45]
How to replace resnet50 with your own backbone？ Has anyone tried replacing backbone?

**Comment by tangjiuqi097** [comment]
Hi, you can replace [this line](https://github.com/megvii-research/AnchorDETR/blob/0b4358a1caacf4b311b8653312e145f1c94de3d3/models/anchor_detr.py#L345) to your own backbone. You may refer to [these codes](https://github.com/megvii-research/SOLQ/blob/97f537ccc3284f7317c99fea1e05567df6663282/models/solq.py#L567-L571) as an example.

**Comment by yao-zheng-yi** [comment]
Okay, thank you very much!

wym ***@***.***> 于2023年2月9日周四 15:25写道：
