### ISSUE TITLE
Is there any way to get the coordinates(polygon shape returns)?

### ISSUE THREAD

**Issue by yellowjs0304** [megvii-research/AnchorDETR#46]
Hi, First of all Thank you for sharing nice work.
I'm beginner of DETR, and i saw your model is better than DETR.

I didn't check the detailed results yet, but i think this model also followed DETR's output like bounding box (x, y, w, h).
Is there any way to get the polygon shaped bbox? (before : x, y, w, h -> after : x1, y1, x2, y2, x3, y3, x4, y4).

**Comment by tangjiuqi097** [comment]
Sorry, we have not tried to predict the polygon shaped box.

**Comment by yellowjs0304** [comment]
i got it. If so, do you have any idea which parts of the architecture must be modified to make quadrilateral shape bboxes?

**Comment by tangjiuqi097** [comment]
Hi, you may refer to the [CornerNet](https://github.com/princeton-vl/CornerNet) or the [rotated object detection methods](https://github.com/open-mmlab/mmrotate).

**Comment by yellowjs0304** [comment]
Thanks for your help.
