### ISSUE TITLE
How to train one's own dataset

### ISSUE THREAD

**Issue by LL-XSJ** [megvii-research/AnchorDETR#48]
How to train one's own dataset

**Comment by tangjiuqi097** [comment]
Hi, you should prepare your own dataset in COCO dataset format, then modified the path in [these lines](https://github.com/megvii-research/AnchorDETR/blob/0b4358a1caacf4b311b8653312e145f1c94de3d3/datasets/coco.py#L161-L165).

**Comment by LL-XSJ** [comment]
Thank you for your reply. I did exactly that, but the training result has always been 0. I don't know why. Could you please reply to me




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/AnchorDETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 中午1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/AnchorDETR] How to train one's own dataset (Issue #48)





 
Hi, you should prepare your own dataset in COCO dataset format, then modified the path in these lines.

**Comment by tangjiuqi097** [comment]
Your data may be not right. You may try to use [this script](https://github.com/facebookresearch/detectron2/blob/main/tools/visualize_data.py) to check it.

**Comment by LL-XSJ** [comment]
My format is correct, I found anchor in the models folder_ After modifying the number of categories in detr.py, the results were all 0 after 50 rounds of training. Of course, I did not load the pre training weights, but I tested it and found that it is not related to whether to load the pre training weights. After I load the pre training weights, the training result is still 0. I guess it may be related to my modification of the number of categories. May I ask the author if I want to modify the anchor after changing the dataset_ What is the number of classes in detr. py?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月9日(星期一) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [megvii-research/AnchorDETR] How to train one&#39;s own dataset (Issue #48)





 
Your data may be not right. You may try to use this script to check it.

**Comment by LL-XSJ** [comment]
How many rounds of training do I need to train my own dataset to converge without using the pre training weights given on the official website?

**Comment by LL-XSJ** [comment]
Excuse me, is the pre training weight you provided on the official website the pre training weight for the entire anchor delta

**Comment by LL-XSJ** [comment]
Hello, may I know how to modify the final category number of the model if I need to

**Comment by tangjiuqi097** [comment]
Hi, the final number of categories should be greater than the largest category index. But if the training result is always 0, in most cases the problem should be caused by the data format. Maybe you can try to use your data to train other detectors to check if the data is correct.
