### ISSUE TITLE
Multiple Predictions for Each Anchor Point

### ISSUE THREAD

**Issue by zhangpeng2001** [megvii-research/AnchorDETR#49]
Hello, I want to enquire about the function of Query Pattern. 
Why did you design multiple patterns for each Position Query rather than setting more Feature Position directly to detect multiple objects whose centers are closed?
Is the function of multiple patterns corresponding to multi-scales or multi-ratio anchors in CNN-based detectors?

**Comment by tangjiuqi097** [comment]
Hi, as shown in Table 4 of the paper, setting more Feature Positions (i.e., 900) cannot significantly improve the performance of 300 Feature Positions. Only more Feature Positions may make the Hungarian matching not as stable when objects have closed centers. As shown in Figure 4 of the paper, the patterns are related to object size but not only the size.
