### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by chenhbo** [megvii-research/AnchorDETR#5]
Hi, 
nice work!

Is there possible to put the pre-trained model up here in the future?
We would like to use the AnchorDETR to train our custom data (no more than 300 images). 
Maybe fine-tuning the pre-trained model is better for us.
Thank you!

**Comment by tangjiuqi097** [comment]
Hi, we have provided the trained models. You can refer to the [readme](https://github.com/megvii-research/AnchorDETR#model).

**Comment by tangjiuqi097** [comment]
I'm closing this issue as I think I have answered your question, but let us know if you have further questions.

**Comment by chenhbo** [comment]
Thank you very much for your reply~
