### ISSUE TITLE
载入预训练模型发现attention 维度不对，可能的问题是 ？

### ISSUE THREAD

**Issue by yelj** [megvii-research/AnchorDETR#50]
谢谢
![image](https://github.com/megvii-research/AnchorDETR/assets/12709373/0dc83efc-fdac-42d8-ac59-ea3173ef8a47)

**Comment by tangjiuqi097** [comment]
请问加载的是哪个预训练模型

**Comment by yelj** [comment]
> 请问加载的是哪个预训练模型
这两个我都试了。相关维度都是1280。。我查看原版detr的预训练模型，都是768啊。
AnchorDETR-C5 | R50 
AnchorDETR-DC5 | R50

**Comment by tangjiuqi097** [comment]
可以看一下这段[代码](https://github.com/megvii-research/AnchorDETR/blob/0b4358a1caacf4b311b8653312e145f1c94de3d3/models/row_column_decoupled_attention.py#L298-L311), channel纬度是256，query key行列各2个再加value 1个, 合计5个256x256的层，拼一起就是1280*256。
如果不想用RCDA可以加 `--attention_type nn.MultiheadAttention`这样就是3个256x256的层，性能是相近的，不过RCDA对显存需求小一些。

**Comment by yelj** [comment]
好的，我明白了。你的模型用的是RCDA 来跑的。。谢谢了。
