### ISSUE TITLE
Performance of the baseline

### ISSUE THREAD

**Issue by ZhangGongjie** [megvii-research/AnchorDETR#7]
Congrats on this awesome work! One quick question: in Table 3 of your paper, without anchor, pattern, and RCDA, the baseline achieves an AP of 39.3% with 50 epoches? It seems strange because it's significantly better than the baseline DETR's result. I wonder what's the real functioning mechanism to facilitate convergence.

Thank you.

**Comment by tangjiuqi097** [comment]
@ZhangGongjie  Hi, 

As the proposed components can improve the performance from 39.3 to 44.2, thus we claim the effectiveness of the proposed method.

But we have not explored the performance of the baseline. 

The difference to DETR-DC5 I can find as follows：
> focal loss for classification, query 100 to 300, dim_feedforward 2048 to 1024, dropout 0.1 to 0

I am not sure if these hyper-parameters contribute to the performance of the DETR.

We also welcome the community to find other differences to DETR together.
