### ISSUE TITLE
how to use custom data

### ISSUE THREAD

**Issue by ffffwyy** [megvii-research/AnchorDETR#8]
i made up a custom dataset and found my training log was wired . i find the class_error is always 0.
before i trained the model , i changed the ”num_classes“ to 2 in "anchor_detr.py" and "transformer.py", cause there is just 1 class .

**Comment by tangjiuqi097** [comment]
Hi, you can refer to [#1](https://github.com/megvii-research/AnchorDETR/issues/1). Or refer to this [gist](https://gist.github.com/m-klasen/651297e28199b4bb7907fc413c49f58f) and the discussion in issues [#9](https://github.com/facebookresearch/detr/issues/9) and [#205](https://github.com/facebookresearch/detr/issues/205) of the DETR directly.

**Comment by tangjiuqi097** [comment]
By the way, it should be normal that the `class_error` is always zero as you only have 1 class.

**Comment by ffffwyy** [comment]
> By the way, it should be normal that the `class_error` is always zero as you only have 1 class.

thanks
