### ISSUE TITLE
num_feature_levels > 1

### ISSUE THREAD

**Issue by yformer** [megvii-research/AnchorDETR#9]
Hello,

When I tried num_feature_levels > 1, the code won't work. This line _srcs = torch.cat(srcs, dim=1)_  in anchor_detr.py shows the mismatch tensor size error. Any ideas to fix it?

**Comment by yformer** [comment]
Yeah, I set num_feature_levels = 3 and use multi-resolution features from different stages. It got the same error. The resolution of feature maps from different stages does not match when doing the torch.cat. I did not see where your code can handle it?

**Comment by tangjiuqi097** [comment]
@yformer Do you make any other modifications? We use three features, i.e. [down-strided C3](https://github.com/megvii-research/AnchorDETR/blob/f688fb0650d5ab21f586355ed0a2314ac7a62c08/models/anchor_detr.py#L48-L63), C4, [dilated C5](https://github.com/megvii-research/AnchorDETR/blob/f688fb0650d5ab21f586355ed0a2314ac7a62c08/models/backbone.py#L105-L106). They have the same size.

**Comment by yformer** [comment]
@tangjiuqi097 , I see. It is down-strided C3, C4, and dilated C5. I directly used the feature maps from different stages. Thanks for your clarification. For the reported results such as _Anchor DETR | DC5 | 50 | 44.2 | 151 | 16 (19)_, does it use down-strided C3, C4, and dilated C5, or just a single dilated C5? With a single dilated C5, I can only get 41.7 AP via training. That is why I was trying num_feature_levels > 1.

**Comment by tangjiuqi097** [comment]
@yformer Hi, it seems that mapping the categories id will not affect the performance. But I recommend you to reproduce the performance without any modification first. The improvement of 3 level feature is about 1 AP and I think your performance gain is reasonable by considering the fluctuation.

**Comment by yformer** [comment]
> @yformer Hi, it seems that mapping the categories id will not affect the performance. But I recommend you to reproduce the performance without any modification first. The improvement of 3 level feature is about 1 AP and I think your performance gain is reasonable by considering the fluctuation.

Yeah, I got the 44.2 AP result when using images per batch 8, learning rate 0.0001. But when I use images per batch 16, learning rate 0.0002, the performance drops to 43.7 AP. For images per batch 32, learning rate 0.0004, the performance further drops to 0. When using multiple (8) nodes for images per batch 8 * 8, learning rate 0.0001 * 8, the performance will also drop 41.2 AP. Any suggestion to fix this?

**Comment by yformer** [comment]
> @yformer how's the speed effected by using 3 level features?

It becomes much slower. It will also make image per batch = 16 out of memory when training on V100s.

**Comment by tangjiuqi097** [comment]
@yformer Hi, the linear scaling rule is too aggressive for the Adamw optimizer. You can try the square-root scaling, e.g. 4 images per card with 8GPU using learning rate 0.0001*2.

By the way, it seems very strange that the performance is 0 for batchsize 32 but is not 0 for batchsize 64.

**Comment by yformer** [comment]
I tried square-root scaling. For batchsize 32, learning rate 0.0002, the performance is 39.39 AP. Did you have a chance to train Anchor-DETR with larger batch size > 8?

**Comment by luohao123** [comment]
@yformer I am training AnchorDETR with BS = 80 now, (8GPUS of 3090). lr=0.00025  Final result will report after fully trained.

**Comment by tangjiuqi097** [comment]
@yformer I have tried the R50-C5 model with batchsize 16 (2 images per card with 8 GPU) to check the `key_padding_mask` for RCDA, and the performances are comparable (41.6 vs. 41.8) and the performances could be the same when carefully adjusts learning rate to 0.00015. I have not tried the larger batchsize after that when the code keeps updating.

BTW, I think this lower performance is not just related to the batchsize and learning rate. Do you have any other modifications?
> For batchsize 32, learning rate 0.0002, the performance is 39.39 AP

**Comment by yformer** [comment]
> @yformer I am training AnchorDETR with BS = 80 now, (8GPUS of 3090). lr=0.00025 Final result will report after fully trained.

@luohao123 Cool. It will be great if you can share your larger batchsize result.

**Comment by yformer** [comment]
> @yformer I have tried the R50-C5 model with batchsize 16 (2 images per card with 8 GPU) to check the `key_padding_mask` for RCDA, and the performances are comparable (41.6 vs. 41.8) and the performances could be the same when carefully adjusts learning rate to 0.00015. I have not tried the larger batchsize after that when the code keeps updating.
> 
> BTW, I think this lower performance is not just related to the batchsize and learning rate. Do you have any other modifications?
> 
> > For batchsize 32, learning rate 0.0002, the performance is 39.39 AP

@tangjiuqi097 You mention the performance is 41.6 when using batchsize 16. Using learning rate = 0.0002, the performance is 41.6, which is 2.7 AP lower than batchsize 8 and learning rate 0.0001. When you change learning rate = 0.00015, the performance increase to 44.3? 

The code is the same except using d2 for data loading and evaluation. Is that possible to train a larger batch size 32 to see the scalability of AnchorDETR?

**Comment by tangjiuqi097** [comment]
> You mention the performance is 41.6 when using batchsize 16. Using learning rate = 0.0002, the performance is 41.6, which is 2.7 AP lower than batchsize 8 and learning rate 0.0001. When you change learning rate = 0.00015, the performance increase to 44.3?

No, it is the R50-C5 model but not R50-DC5. The performance of the R50-C5 model in that version is 41.8.

**Comment by tangjiuqi097** [comment]
> The code is the same except using d2 for data loading and evaluation. Is that possible to train a larger batch size 32 to see the scalability of AnchorDETR?

Could you try our original code but not the d2 version for batchsize 32? You can run the command: 
```
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py  --lr 2e-4 --lr_backbone 2e-5 --batch_size 4 --coco_path /path/to/coco 

```

**Comment by luohao123** [comment]
@yformer @tangjiuqi097 I found that AnchorDETR at the begaining converge fast, but after that, the AP can not goes up:

![image](https://user-images.githubusercontent.com/49749220/140446472-d180add1-83b6-4a1a-a1ca-c9e34ce8277f.png)

this is the AP at 179999 -> 28.9

![image](https://user-images.githubusercontent.com/49749220/140446510-facb8d48-002d-4ffc-a81d-67c65c500eea.png)

this is the AP at 149999 -> 29.5

It seems stoped at 28.9 can not goes up anymore.....

**Comment by tangjiuqi097** [comment]
@luohao123 Hi, I am not sure whether the problem is due to the learning rate not being suitable for batch size or the code implementation. Can you try our default setting to find if your code can reproduce the performance?

**Comment by luohao123** [comment]
@tangjiuqi097 I think models exactly same as anchordetr, and I fixed SetCriterion problem make it all same, as well as HugrianMachter. The finally problem must be lr schedualer.

But the lr schdualer, is same as DETR, but lr fom 0.0001 -> 0.00025. 

Also, since the first serveral iteration shows fast converge speed, and actually it at least work, so maybe the model don't have any problem, the final issue could be the lr ..

**Comment by yformer** [comment]
@tangjiuqi097 , I tried batchsize = 16, 32, 64, 128. I could not obtain the reported performance. I wonder if you can run a larger batchsize (> 8) to reproduce the performance?

**Comment by luohao123** [comment]
@yformer I think is not about batchsize, doesn means we using batchsize 8 can reproduces ops accuracy.

It has some deep problem hard to investigate, Currently, I trained about 25000, and the AP can not goes up anymore....

AP 30 is the highest score currently:


![image](https://user-images.githubusercontent.com/49749220/140879377-2c8045f4-8339-4ecd-b42f-41972135312e.png)

So the model actually only get AP 30??

**Comment by tangjiuqi097** [comment]
> @yformer I think is not about batchsize, doesn means we using batchsize 8 can reproduces ops accuracy.
> 
> It has some deep problem hard to investigate, Currently, I trained about 250000, and the AP can not goes up anymore....
> 
> AP 30 is the highest score currently:
> 
> ![image](https://user-images.githubusercontent.com/49749220/140879377-2c8045f4-8339-4ecd-b42f-41972135312e.png)
> 
> So the model actually only get AP 30??

I think the d2 version you reproduced may not right. Can you try our official code?

**Comment by tangjiuqi097** [comment]
> @tangjiuqi097 , I tried batchsize = 16, 32, 64, 128. I could not obtain the reported performance. I wonder if you can run a larger batchsize (> 8) to reproduce the performance?

@yformer  What are the performances you trained? Do you use our official code or your reproduced d2 version code?

**Comment by yformer** [comment]
> > @tangjiuqi097 , I tried batchsize = 16, 32, 64, 128. I could not obtain the reported performance. I wonder if you can run a larger batchsize (> 8) to reproduce the performance?
> 
> @yformer What are the performances you trained? Do you use our official code or your reproduced d2 version code?

For batchsize 8 x 16 and learning rate 0.00025, the performance is 41.96. I used d2 version code, which can scale for a larger size.

**Comment by luohao123** [comment]
@yformer What's your SOLVER configs? Can you share it? How do you make steps in Multisteps learning schedualer?

**Comment by yformer** [comment]
@luohao123 I trained the model with 50 epochs using batchsize 16 x 8. The initial learning rate is 0.00025 and decay the learning rate with 0.1 at 40 epochs. The optimizer is ADAMW with 10 warmup iterations.

**Comment by tangjiuqi097** [comment]
@yformer This result is much higher than your previous results. It still has about 2 AP gaps to our results with batchsize 8, but I think the gap within 1AP should be more reasonable. I am concerned about your d2 version whether it can reproduce the performance even with the same batchsize. Have you solved the problem in #16? If you want to train the model with multiple nodes, you can follow the instruction in [DETR](https://github.com/facebookresearch/detr/blob/091a817eca74b8b97e35e4531c1c39f89fbe38eb/run_with_submitit.py) instead of the d2 version. BTW, can you try the setting that 1 image per card, 8 cards per node, and multiple nodes? I wonder if it is related to the padding region.

**Comment by luohao123** [comment]
@yformer that make no sense, d2 doesn't have a concept of epoch, it's all iterations.
Can you share your d2 config file?

**Comment by luohao123** [comment]
@tangjiuqi097 I just curious about why don't your experiment on bs > 8 on your side? what's that performance?

**Comment by yformer** [comment]
@luohao123 You can convert it to iterations since they are equivalent. My implementation is scaled for multiple machines. So that is why I shared the epochs. The equivalent iterations is 46200. 

 IMS_PER_BATCH: 128
 BASE_LR: 0.00025

 STEPS: (36960,)  
 MAX_ITER: 46200

Other hyperparameters are the same as those you shared.

**Comment by yformer** [comment]
> @yformer This result is much higher than your previous results. It still has about 2 AP gaps to our results with batchsize 8, but I think the gap within 1AP should be more reasonable. I am concerned about your d2 version whether it can reproduce the performance even with the same batchsize. Have you solved the problem in #16? If you want to train the model with multiple nodes, you can follow the instruction in [DETR](https://github.com/facebookresearch/detr/blob/091a817eca74b8b97e35e4531c1c39f89fbe38eb/run_with_submitit.py) instead of the d2 version. BTW, can you try the setting that 1 image per card, 8 cards per node, and multiple nodes? I wonder if it is related to the padding region.

For batchsize = 8, the result can be reproduced. I did not resolve that issue. I do not know why it happened. Sometimes it did not show up. I tried 8x8 images per batch, the result is quite similar to 16x8 images per batch.

**Comment by luohao123** [comment]
@yformer bs=8 means 1img/per gpu? Or 8 image per gpu?

You are not possible training 46200 get AP 42. You need at least 200000 iterations to get a resonable performance.

**Comment by yformer** [comment]
@luohao123 , bs = 8 means 1 img/per gpu. It trains more than 200K iterations. For 46200, it is 16 x 8 images per batch.

**Comment by luohao123** [comment]
@yformer Can u share your d2 code train AnchorDETR? Or your config? I currenty using bs=80, after 200k, I only get mAP 36

**Comment by tangjiuqi097** [comment]
@luohao123 Currently, I do not have enough cards for these experiments with large batches.

**Comment by tangjiuqi097** [comment]
@yformer  It should be too aggressive to increase the batchsize from 8 to 128. Especially, the Adamw optimizer does not obey the  linear scaling rule well. I suggest using batchsize 16 or 32 first.

**Comment by yformer** [comment]
> @yformer It should be too aggressive to increase the batchsize from 8 to 128. Especially, the Adamw optimizer does not obey the linear scaling rule well. I suggest using batchsize 16 or 32 first.

@tangjiuqi097, based on my experiments, it seems the anchordetr does not scale well with large batch size. Coupling with other heads instead of anchor-detr, the performance of my implementation is very consistent. Any ideas why it happens, e.g., the approximate self-attention?

**Comment by tangjiuqi097** [comment]
@yformer You can try to use the standard attention by setting [`--attention_type nn.MultiheadAttention`](https://github.com/megvii-research/AnchorDETR/blob/1f0b1c1a1388aebcc9ea6462650750db78d54c88/main.py#L75-L79) to  investigate if the standard attention has this phenomenon.
